name: Build & Push Telegraf Images

on:
  push:
    paths:
      - 'telegraf_*/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workdir:
          - telegraf_sys_pi
          # spÃ¤ter einfach erweitern:
          # - telegraf_sys_amd64

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load image config
        run: |
          cd ${{ matrix.workdir }}

          set -o allexport
          source build.env
          source version.txt
          set +o allexport

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
          echo "TELEGRAF_VERSION=$TELEGRAF_VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "WORKDIR=${{ matrix.workdir }}" >> $GITHUB_ENV

      - name: Define image tags
        run: |
          echo "TAG_BUILD=${TELEGRAF_VERSION}-${BUILD}" >> $GITHUB_ENV
          echo "TAG_VERSION=${TELEGRAF_VERSION}" >> $GITHUB_ENV
          echo "TAG_LATEST=latest" >> $GITHUB_ENV

      - name: Check for existing cache
        id: cache-check
        run: |
          docker pull ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:cache || echo "no-cache"
          echo "CACHE_EXISTS=$(docker image inspect ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:cache >/dev/null 2>&1 && echo true || echo false)" >> $GITHUB_ENV

        if: env.CACHE_EXISTS != 'true'
        run: |
          docker buildx build \
            --platform ${{ env.PLATFORM }} \
            --build-arg TELEGRAF_VERSION=${TELEGRAF_VERSION} \
            -t ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG_X} \
            --cache-from=type=registry,ref=${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:cache \
            --cache-to=type=registry,ref=${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:cache,mode=max \
            --push \
            ${{ env.WORKDIR }}
