name: Build & Push Telegraf Images

on:
  push:
    paths:
      - 'telegraf_*/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workdir:
          - telegraf_sys_pi
          # spÃ¤ter einfach erweitern:
          # - telegraf_sys_amd64

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load image config
        run: |
          cd ${{ matrix.workdir }}

          set -o allexport
          source build.env
          source version.txt
          set +o allexport

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
          echo "TELEGRAF_VERSION=$TELEGRAF_VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      - name: Define image tags
        run: |
          echo "TAG_BUILD=${TELEGRAF_VERSION}-${BUILD}" >> $GITHUB_ENV
          echo "TAG_VERSION=${TELEGRAF_VERSION}" >> $GITHUB_ENV
          echo "TAG_LATEST=latest" >> $GITHUB_ENV

      - name: Debug vars
	run: |
	  echo "matrix.workdir = ${{ matrix.workdir }}"
	  echo "IMAGE_NAME=$IMAGE_NAME"
	  echo "PLATFORM=$PLATFORM"
	  echo "TELEGRAF_VERSION=$TELEGRAF_VERSION"

      - name: Build & push image
        run: |
          docker buildx build \
            --platform $PLATFORM \
            --build-arg TELEGRAF_VERSION=$TELEGRAF_VERSION \
            -t $DOCKER_USER/$IMAGE_NAME:$TAG_BUILD \
            -t $DOCKER_USER/$IMAGE_NAME:$TAG_VERSION \
            -t $DOCKER_USER/$IMAGE_NAME:$TAG_LATEST \
            --push \
            "${{ matrix.workdir }}"

