name: Build & Push Grafana Image

on:
  push:
    #paths:
    #  - 'Dockerfile'
    #  - 'provisioning/**'
    #  - 'dashboards/**'
  workflow_dispatch:

jobs:
  build-grafana:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-24.04-arm  # oder ubuntu-22.04-arm

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
      GRAFANA_VERSION: 10.1.4    # hier die gew√ºnschte Version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Grafana Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: true
          build-args: |
            GRAFANA_VERSION=${{ env.GRAFANA_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/grafana:${{ env.GRAFANA_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/grafana:latest

