name: Build & Push Telegraf Images

on:
  push:
    #paths:
    #  - 'telegraf_*/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir:
          - telegraf_sys_pi
          # weitere Images hier hinzufügen, z.B. telegraf_sys_amd64

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load image config
        run: |
          # Entfernt mögliche Windows-Zeilenenden
          sed -i 's/\r$//' "${{ matrix.workdir }}/build.env"
          sed -i 's/\r$//' "${{ matrix.workdir }}/version.txt"

          # ENV & Version laden
          source "${{ matrix.workdir }}/build.env"
          source "${{ matrix.workdir }}/version.txt"

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
          echo "TELEGRAF_VERSION=$TELEGRAF_VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "WORKDIR=${{ matrix.workdir }}" >> $GITHUB_ENV

      - name: Define image tags
        run: |
          echo "TAG_BUILD=${TELEGRAF_VERSION}-${BUILD}" >> $GITHUB_ENV
          echo "TAG_VERSION=${TELEGRAF_VERSION}" >> $GITHUB_ENV
          echo "TAG_LATEST=latest" >> $GITHUB_ENV

      - name: Debug environment
        run: |
          echo "WORKDIR=$WORKDIR"
          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "PLATFORM=$PLATFORM"
          echo "TELEGRAF_VERSION=$TELEGRAF_VERSION"
          echo "TAG_BUILD=$TAG_BUILD"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.workdir }}
          file: ./${{ matrix.workdir }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            TELEGRAF_VERSION=${TELEGRAF_VERSION}
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${TAG_BUILD}
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${TAG_VERSION}
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest

